import { Button, Container } from 'react-bootstrap';
import PageShell from '../layouts/PageShell';
import SectionIntro from '../components/SectionIntro';
import { categories, destinations, journeys } from '../data/mockData';

export default function HomePage({ onSelect }) {
  return <PageShell active="home"><section className="hero-stage" id="top"><Container fluid className="hero-grid"><div className="hero-copy" data-reveal><div className="eyebrow"><span className="eyebrow-line" /> Nhật ký miền gió biển</div><h1>Đi về phía<br /><em>một Hà Tĩnh</em><br />rất riêng.</h1><p>Biển xanh, núi Hồng, những câu chuyện cũ và vị quê ở lại rất lâu.</p><div className="hero-actions"><Button className="btn-coral" href="#/destinations">Khám phá điểm đến <span>↘</span></Button><a className="text-action" href="#/journeys">Xem lộ trình <span>↗</span></a></div></div><div className="hero-collage" data-reveal><figure className="hero-main-image"><img src="/bien-thien-cam-hoang-hon.jpg" alt="Biển Thiên Cầm lúc hoàng hôn" /><figcaption><strong>01</strong><span>Biển Thiên Cầm<br /><small>Cẩm Xuyên, Hà Tĩnh</small></span></figcaption></figure><figure className="hero-small-image"><img src="/nui-hong-linh-commons.jpg" alt="Núi Hồng Lĩnh" /><span>Núi Hồng Lĩnh<br /><small>nhìn từ Can Lộc</small></span></figure><div className="hero-stamp">HÀ<br />TĨNH<br /><span>✳</span></div></div></Container><div className="hero-bottom"><span>Đất & nước / 2026</span><span>Cuộn để khám phá <b>↓</b></span><span>18°32'N · 105°54'E</span></div></section><section className="manifesto site-section"><Container fluid><div className="manifesto-mark">✳</div><p>Hà Tĩnh không ồn ào để gây ấn tượng.<br /><em>Nó ở lại bằng những điều rất thật.</em></p><span>Đất / nước / ký ức / vị quê</span></Container></section><section className="site-section"><Container fluid><SectionIntro eyebrow="Khám phá nhanh" title={<>Những nơi đáng <em>nhớ.</em></>} action={<a className="text-action" href="#/destinations">Xem tất cả <span>↗</span></a>} /><div className="destination-grid">{destinations.slice(0, 4).map((item, index) => <div key={item.id}><DestinationPreview item={item} index={index} onSelect={onSelect} /></div>)}</div></Container></section><section className="category-section site-section"><Container fluid><SectionIntro eyebrow="Đi theo cảm hứng" title={<>Một vùng đất,<br /><em>nhiều cách chạm.</em></>} /><div className="category-grid">{categories.map(([number, title, description]) => <a href="#/destinations" className="category-row" key={title}><span>{number}</span><h3>{title}</h3><p>{description}</p><b>↗</b></a>)}</div></Container></section><section className="journeys-section site-section"><Container fluid><SectionIntro eyebrow="Đã sắp xếp cho bạn" title={<>Lên đường theo<br /><em>một nhịp khác.</em></>} action={<a className="text-action" href="#/journeys">Xem hành trình <span>↗</span></a>} /><div className="journey-grid">{journeys.map((journey, index) => <article className={`journey-item journey-item-${index + 1}`} key={journey.id}><img src={journey.image} alt={journey.title} /><div className="journey-overlay"><span>{journey.meta}</span><h3>{journey.title}</h3><p>{journey.stops.join(' · ')}</p></div></article>)}</div></Container></section></PageShell>;
}

function DestinationPreview({ item, index, onSelect }) {
  return <article className={`destination-card tone-${item.tone}`} onClick={() => onSelect(item)}><div className="card-image-wrap"><img src={item.image} alt={item.name} /><span className="image-index">0{index + 1}</span></div><div className="card-body"><div className="card-location">{item.area} · {item.type}</div><h3>{item.name}</h3><p>{item.note}</p><button className="round-arrow" aria-label={`Mở ${item.name}`}>↗</button></div></article>;
}
